pipeline{
    agent any

    stages {
        stage('Get Source'){
            steps{
                git url: 'https://github.com/arturcorreiajr/desafio-ouze.git', branch: 'main'
            }

        }
        stage('Docker Build API1'){
            steps{
                script {
                    dockerapp = docker.build("arturcorreiajunior/api1:${env.BUILD_ID}", '-f ./api1/Dockerfile .')
                }
            }
        }
        stage('Docker Push API1'){
            steps{
                script {
                        docker.withRegistry('http://registry.hub.docker.com', 'github-token-jenkins'){
                        dockerapp.push('latest')
                        dockerapp.push("${env.BUILD_ID}")
                }
                }
            }
        }

        stage('Deploy docker'){
            steps{
                script {
                    echo "arturcorreiajunior/api1:${env.BUILD_ID}"
                    sh "docker stop api1 || true && docker rm api1 || true"
                    sh "docker run --name api1 -d -p 8080:80 arturcorreiajunior/api1:${env.BUILD_ID}"
                }
            }
        }

    }

}