pipeline{
    agent any

    stages{
        stage('Build Backend'){
            steps{
                sh 'cd ..'
                sh 'cd ./tasks-backend/'
                sh 'mvn clean package -DskipTests=true'
            }
        }
    }
}